version: '3.4'

services:
  cleanarch.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      # - ASPNETCORE_HTTPS_PORTS=443
      - "ConnectionStrings:ConnStr=Server=sqlserver,1433; Database=CleanArchitecture; User=sa; Password=Sa123456; TrustServerCertificate=True"
      - "RedisConnection=redis"
    ports:
      - "5000:80"
      # - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  cleanarch.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      # - ASPNETCORE_HTTPS_PORTS=443
      - BaseApiUrl=http://cleanarchapi_container:80
    ports:
      - "8000:80"
      # - "8001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  sqlserver:
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Sa123456  # Set your SQL Server password
    ports:
       - "1433:1433"
    volumes:
      - sqlserver_volume:/var/opt/mssql

  redis:
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    
